// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh8uZ--I0BAJnhLf4F8uC75FSejldJ_yY',
    appId: '1:37218947084:web:36be78ce26b4898ad0de29',
    messagingSenderId: '37218947084',
    projectId: 'booking-cms-155yg',
    authDomain: 'booking-cms-155yg.firebaseapp.com',
    storageBucket: 'booking-cms-155yg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDthlXLODltpVTJq5kGXxmY4xKd-WC_NEA',
    appId: '1:37218947084:android:415fe3965a5d4043d0de29',
    messagingSenderId: '37218947084',
    projectId: 'booking-cms-155yg',
    storageBucket: 'booking-cms-155yg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QSsbjc6VFah6KSQUjOq6wW8ZUNU9A0c',
    appId: '1:37218947084:ios:f1a67e6060cf1059d0de29',
    messagingSenderId: '37218947084',
    projectId: 'booking-cms-155yg',
    storageBucket: 'booking-cms-155yg.appspot.com',
    iosBundleId: 'com.example.cmsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2QSsbjc6VFah6KSQUjOq6wW8ZUNU9A0c',
    appId: '1:37218947084:ios:f1a67e6060cf1059d0de29',
    messagingSenderId: '37218947084',
    projectId: 'booking-cms-155yg',
    storageBucket: 'booking-cms-155yg.appspot.com',
    iosBundleId: 'com.example.cmsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh8uZ--I0BAJnhLf4F8uC75FSejldJ_yY',
    appId: '1:37218947084:web:f0fc53dbaa63b34ad0de29',
    messagingSenderId: '37218947084',
    projectId: 'booking-cms-155yg',
    authDomain: 'booking-cms-155yg.firebaseapp.com',
    storageBucket: 'booking-cms-155yg.appspot.com',
  );
}
